name: test

on:
  pull_request

jobs:
  test:
    name: Run tests for Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"  # Oldest supported
          - "25" # Latest release (LTS)

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: make build

      - name: Run tests
        run: make test